trigger:
- master

resources:
  repositories:
  - repository: templates
    type: github
    name: JeringTech/DevOps.AzurePipelines
    endpoint: JeringTech

jobs:
- template: templates/nuget/main.yml@templates
  parameters:
    outOfProcessBuildDependencies: ["nodejs"]
    cacheYarnPackages: true
- template: templates/docs/main.yml@templates
  parameters:
    nugetRestorePats: "$(nugetRestorePats)"
